version: '3.9'

services:
  api:
    container_name: tex-api
    build: .
    restart: always
    stdin_open: true
    tty: true
    ports:
      - '<port>:<port>'
    env_file:
      - priv/prod.env
